# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "eu-west-1"
    bucket  = "tf-state.exposed.dev"
  }
}
